---
# this arc-theme repo displays a verification failed error
# so we download deb file and install from file.
#    - "deb https://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_16.04/ /"
    
# - name: Add Arc theme key
#   apt_key:
#     url: http://download.opensuse.org/repositories/home:Horst3180/xUbuntu_16.04/Release.key
#     state: present

# - name: Add Skype key
#   apt_key:
#     url: https://repo.skype.com/data/SKYPE-GPG-KEY
#     state: present
- name: Add repo
  apt_repository: 
    repo: "{{item}}"
    state: present
  with_items:
    - "deb http://eddie.website/repository/apt stable main"
    - ppa:nextcloud-devs/client
    - "deb [arch=amd64] https://download.newrelic.com/infrastructure_agent/linux/apt xenial main"
    - ppa:phoerious/keepassxc
    - "deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main"
    # - ppa:peek-developers/stable

- name: Remove arc theme repo
  apt_repository:
    repo: ppa:moka/daily
    state: absent

- name: Accept the EULA for MS core fonts
  shell: "echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections"

- name: Remove Keepass CX from Snap
  tags:
    - keepassxc
  shell: snap remove keepassxc

- name: Install all necessary packages and update the system
  apt: name={{item}} state=present update_cache=true force=yes
  with_items:
    - apt-transport-https

    # - peek
    # - skypeforlinux # <- not in cosmic repo again
    # - slack-desktop # <- not in cosmic repo again

- name: Install all packages on cosmic
  apt: name={{item}} state=present update_cache=true force=yes
  with_items:
    - peek
  when: ansible_distribution_release == 'cosmic'



- copy:
    src: "../files/{{item}}"
    dest: "/tmp/{{item}}"
  with_items: "{{bundled_packages}}"

- name: Install packages from bundled deb files
  apt:
    deb: "/tmp/{{item}}"
    state: present
    #force: yes
  with_items: "{{bundled_packages}}"
  ignore_errors: true

- name: Download bundled packages to /tmp/
  get_url:
    url: "{{item}}"
    dest: "/tmp/{{item | basename}}"
  with_items: "{{bundled_urls}}"
  
- name: Install packages from bundled urls
  apt:
    deb: "/tmp/{{item | basename}}"
    state: present
  with_items: "{{bundled_urls}}"
  ignore_errors: true
