---
- name: Check if Brother is installed
  tags:
    - printer
  stat:
    path: /etc/cups/ppd/Brother.ppd
  register: brother

- name: Install Brother printer
  tags:
    - printer
  shell: "(
  cd /opt/brother/Printers/MFCL5700DN/lpd;
  lpadmin -p Brother -E -v 'http://Brother MFC-L5700DN series._ipp._tcp.local:631')"
  when: brother.stat.exists == False


- name: Set Brother papersize to A4
  tags:
    - printer
  shell: "lpadmin -p Brother -o PageSize=A4"
  when: brother.stat.exists == False
